name: portfolio
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # essential
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  shared_preferences: ^2.3.2
  provider: ^6.1.2
  url_strategy: ^0.3.0
  url_launcher: ^6.3.1
  flutter_blurhash: ^0.8.2
  intl: ^0.19.0

  # UI 
  syncfusion_flutter_calendar: ^29.1.39
  syncfusion_flutter_charts: ^29.1.39
  syncfusion_flutter_maps: ^29.1.39
  appflowy_board: ^0.1.2
  flutter_colorpicker: ^1.1.0
  file_picker: ^8.0.2
  image_picker: ^1.1.2
  font_awesome_flutter: ^10.7.0
  google_maps_flutter: ^2.12.1
  google_fonts: ^6.2.1
  countup: ^0.1.4
  # timelines: ^0.1.0
  fl_chart: ^0.71.0
  flutter_svg: ^2.0.10+1

  flutter_lucide: ^1.6.2
  flutter_quill: ^11.4.0
  appflowy_editor: ^5.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/auth/
    - assets/images/logo/
    - assets/images/dummy/
    - assets/lang/
    - assets/data/
    - assets/images/food/

